export const assessmentLabels = {
  codingConfidence: {
    hello_world: "Write a basic 'Hello World' program",
    simple_projects: "Build simple projects (e.g., calculator, to-do list)",
    use_apis: "Use APIs, libraries, or frameworks",
    full_apps: "Build full apps with both frontend and backend",
    not_sure: "I'm not sure yet",
  },
  programmingLanguages: {
    html_css: "HTML / CSS",
    javascript: "JavaScript",
    python: "Python",
    java_cpp: "Java / C++",
    none: "None yet",
  },
  csUnderstanding: {
    not_familiar: "I'm not familiar with computer science concepts",
    basics: "I've used programming basics (variables, loops, functions)",
    ds_algo: "I know data structures and algorithms",
    systems: "I've studied systems (OS, memory, networking)",
    theory_confident: "I'm confident in computer science theory",
  },
  csTopics: {
    arrays_lists: "Arrays, Linked Lists",
    big_o: "Big O Notation",
    recursion: "Recursion",
    http_tcp_dns: "HTTP / TCP / DNS",
    memory_threads: "Virtual Memory, Threads",
    none: "None of these",
  },
  problemSolving: {
    not_yet: "Not yet",
    few_problems: "Solved a few beginner-level problems",
    regular: "I solve problems regularly",
    timed_challenges: "I've done timed or competitive challenges",
  },
  tools: {
    editors: "Code editors (VS Code, Sublime, etc.)",
    git: "Git / GitHub",
    browser_devtools: "Browser DevTools",
    terminal: "Terminal / Command Line",
    none: "None of these",
  },
  weeklyCommitment: {
    lt3: "Less than 3 hours",
    "3_5": "3–5 hours",
    "6_10": "6–10 hours",
    gt10: "More than 10 hours",
  },
  mainGoal: {
    get_job: "Get my first job",
    freelance: "Start freelancing",
    projects: "Learn by building real projects",
    exploring: "Just exploring / not sure yet",
  },
  confidence: {
    getting_started: "I'm just getting started",
    few_basics: "I know a few basics",
    simple_projects: "I can build simple projects",
    full_apps_help: "I can build full apps with some help",
    confident: "I'm confident and self-directed",
  },
  interests: {
    web: "Web Development",
    mobile: "Mobile Apps",
    game: "Game Development",
    data_ai: "Data Science / AI",
    not_sure: "Not sure yet",
  },
  learningStyle: {
    video: "Watching video tutorials",
    reading: "Reading articles or books",
    projects: "Building real-world projects",
    help_when_stuck: "Getting help when I'm stuck",
    mix: "A mix of all",
  },
};
